### ISSUE TITLE
load_videos.py - Can not load video UW1c9E8nfxQ, broken link

### ISSUE THREAD

**Issue by brbernardo90** [zhengkw18/face-vid2vid#10]
Hi! Thank you for your great contribution! I would love to use your model! I'm trying to build the default dataset folder but:

`python load_videos.py --workers=8`

Number of videos: 3442
0it [00:00, ?it/s]Can not load video UW1c9E8nfxQ, broken link
1it [00:08,  8.73s/it]Can not load video pbm-5KhWXlc, broken link
2it [00:10,  4.82s/it]Can not load video tMP5U3jYNkg, broken link
Can not load video LZ_Hw9J62KE, broken link
4it [00:10,  1.84s/it]Can not load video u3odsIbYouc, broken link
Can not load video yLA2n3coUgk, broken link
6it [00:11,  1.01s/it]Can not load video ULBH3A8DjPM, broken link
Can not load video B5jqlhXWkOo, broken link
8it [00:11,  1.59it/s]Can not load video LNlufCgIx_E, broken link
Can not load video shR-y9jzeHg, broken link
10it [00:22,  2.44s/it]Can not load video 8xomuTM5Jm8, broken link
Can not load video zWig265SViA, broken link
Can not load video q1mNeW_BrSw, broken link
13it [00:22,  1.42s/it]Can not load video vN5K8HEgafI, broken link
Can not load video ldAbe81ePpE, broken link
15it [00:22,  1.02s/it]Can not load video daZUIa8FA_M, broken link
Can not load video dwnIdViJS0U, broken link
17it [00:26,  1.23s/it]Can not load video QdBQTHX55yI, broken link
18it [00:33,  2.25s/it]Can not load video 1fpTDuFfoB0, broken link
19it [00:33,  1.83s/it]Can not load video DE089Obo6L4, broken link
20it [00:33,  1.46s/it]Can not load video sh6J3wEmceA, broken link
21it [00:33,  1.14s/it]Can not load video Hyzl8482nfY, broken link
22it [00:33,  1.14it/s]Can not load video vuVdwmx_1yQ, broken link

Can you help me?!

**Comment by zhengkw18** [comment]
Some video links may be invalid since they come from Youtube. It seems that you can't reach any of the links. You should check whether you have access to those Youtube videos, for example visit the sites directly.

**Comment by brbernardo90** [comment]
@zhengkw18 Thanks for your quick reply. 

You are right, but I tried to access the videos directly and some are possible and some no longer exist. I tried to solve it but i couldn't. Anyway, I have my own dataset and I am trying understand how to organize my dataset to adapt to your model. Can you help me?

Each lesson of my dataset is composed by:
- The file keypoints txt (**driving**, **array shape** = [168,2]);
- A folder with the frames png (**target video**, **img size** = [256,256])
.
└── facedataset/
    ├── test_img/
    │   ├── video_name_1/
    │   │   ├── 00001.png
    │   │   ├── 00002.png
    │   │   ├── 00003.png
    │   │   └── ...
    │   ├── video_name_2
    │   └── video_name_3
    ├── test_keypoints/
    │   ├── video_name_1/
    │   │   ├── 00001.txt
    │   │   ├── 00002.txt
    │   │   ├── 00003.txt
    │   │   └── ...
    │   ├── video_name_2
    │   └── video_name_3
    ├── train_img
    └── train_keypoints

**Comment by zhengkw18** [comment]
You only need to prepare folders with the frames png, because we extract the headpose using off-the-shelf model, and learn a 3D keypoint estimator from scratch. The folder structure is:
├──datasets/vox/train/
│ ├── id1#video1/
│ │ ├── 00001.png
│ │ ├── 00002.png
│ │ ├── 00003.png
│ │ └── ...
│ ├── id1#video2
│ └── ...
│ ├── id2#video3
│ └── ...

Note that every folder contains frames png of a segment of a talking head video, and the folder should be named as id#video. The "#" is necessary, because we enable "id sampling". We'll view the name part before "#" as the person id, and uniformly sample the id, see `dataset.py`.
