### ISSUE TITLE
There is a problem with the generated video, what is the cause?

### ISSUE THREAD

**Issue by applech666** [zhengkw18/face-vid2vid#6]
Thank you for your shared model!
![output](https://user-images.githubusercontent.com/71813266/142344972-2330ea1f-50f4-45d3-893e-9e6bc1f3712a.gif)
 
I used your pre-trained model.
What's the problem?

thanks!

**Comment by applech666** [comment]
I used your pre-trained model.
What's the problem?

**Comment by zhengkw18** [comment]
Which did you use, motion transfer or reconstruction? I guess there is problem with your source image.

**Comment by applech666** [comment]
![test](https://user-images.githubusercontent.com/71813266/142348138-e0afee9d-1914-4d77-96e4-08d68acc7172.png)

**Comment by zhengkw18** [comment]
This is strange. You can try other source/driving to see which causes the problem. Several reasons are possible:
1. driving has bad illumination
2. source/driving face should be resized
3. source jpg format image is not correctly read
4. Asian people are out of the training dataset distribution so not properly modeled

**Comment by applech666** [comment]
According to your suggestion, I changed the driving video and the original image, but the result is still terrible.
generated:
![output](https://user-images.githubusercontent.com/71813266/142362339-38ff0261-c76b-4fa0-8ff5-29a749b85c01.gif)
drive video:
![0000000](https://user-images.githubusercontent.com/71813266/142362388-f72baca6-b7d9-4bc2-ae8a-e8e2cabf7f51.png)
source image:
![test](https://user-images.githubusercontent.com/71813266/142362446-97e83c59-2de9-4d77-9859-52f4a5aa7d3d.png)

run command:
python evaluate.py --ckp=100 --source=test.png --driving=datasets/vox/test/id10070#FWHkEnS8v-M#001286#001433.mp4

**Comment by applech666** [comment]
How do I understand it here?

![1637216932(1)](https://user-images.githubusercontent.com/71813266/142364127-97a8cdd6-7892-4d23-ab49-084e3cd0d49e.png)

**Comment by zhengkw18** [comment]
Now I think this is due to environment problems such as Pytorch version...For some reasons the pretrained model or the image is not correctly loaded. The headpose estimator is used during training so it's irrelevant.

**Comment by applech666** [comment]
I'm using torch==1.6. What about you?

**Comment by zhengkw18** [comment]
You can update all your packages to latest version. Besides you can re-clone the repo to confirm there is no code change.

**Comment by applech666** [comment]
![output](https://user-images.githubusercontent.com/71813266/142372634-f19a6016-91a4-4e28-a686-7e4e38e479aa.gif)
thanks @zhengkw18 
I made a mistake in solving the problem:
RuntimeError: Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.
