### ISSUE TITLE
training data and command

### ISSUE THREAD

**Issue by 805094591** [zhengkw18/face-vid2vid#9]
Hello～Thank you for your great contribution~
I want to know how to train on this project~Which format（A series of folders containing video frames（pictures） or a series of videos or others） and directory are the data put into during training? What are the corresponding python training commands? 
Thank you～

**Comment by zhengkw18** [comment]
For the default dataset preparation, I list the commands in `README.md`
```
cd datasets
wget https://yt-dl.org/downloads/latest/youtube-dl -O youtube-dl
chmod a+rx youtube-dl
python load_videos.py --workers=8
cd ..
```
The folder structure for the dataset is `/datasets/vox/train`,`/datasets/vox/test` containing a series of folders of video frames e.g. `/datasets/vox/train/id10001#J9lHsKG98U8#00001.txt#000.mp4/0000000.png`.
Python training commands are also listed in `README.md`, like
```
python train.py --batch_size=4 --gpu_ids=0,1,2,3 --num_epochs=100 (--ckp=10)
```

**Comment by 805094591** [comment]
Training runs well~Thank you~

**Comment by 805094591** [comment]
Training runs well~
Thank you very much~
